---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: moody
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
# base-image: ghcr.io/ublue-os/bazzite-gnome-nvidia-open
# Switch to -dx- base when https://github.com/ublue-os/bazzite-dx builds ar successful for :42
# base-image: ghcr.io/ublue-os/bazzite-dx-gnome-nvidia-open
# image-version: 42 # latest is also supported if you want new updates ASAP
base-image: ghcr.io/ublue-os/bluefin-dx-nvidia-open
image-version: stable

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      - https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo
    optfix:
      - brave.com
    keys:
      - https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
    install:
      - brave-browser
      - firefox
      - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
      
  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      install:
        - org.gnome.Loupe
        - org.signal.Signal
        - io.github.milkshiift.GoofCord # Discord has an error log which effectively keystroke logs into the system log
        - com.slack.Slack
        - md.obsidian.Obsidian
        - org.freedesktop.Sdk.Extension.texlive//24.08 # pdflatex support for obsidian
        - de.capypara.FieldMonitor
        - com.bambulab.BambuStudio
      remove:
        # Don't recall which of these causes issues with 1password GUI and browser extentions, but no flatpak browsers here thanks
        # https://github.com/flatpak/xdg-desktop-portal/pull/1537
        # 1537 replaces 705 https://github.com/flatpak/xdg-desktop-portal/pull/705#issuecomment-2752147296
        # https://github.com/flatpak/xdg-desktop-portal/issues/655#issuecomment-2848732249
        - org.mozilla.firefox
        - org.gnome.eog
    user: {} # Also add Flathub user repo, but no user packages

  - type: bling
    install:
      - 1password
#  - type: chezmoi
#    repository: "https://github.com/billm/dotfiles"
#    file-conflict-policy: replace
  - type: brew
    nofile-limits: true
    auto-update: true
    auto-upgrade: true
    brew-analytics: false
  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode # don't add spaces or "Nerd Font" suffix.
        - Hack
        - SourceCodePro
        - Terminus
        - JetBrainsMono
        - NerdFontsSymbolsOnly
      google-fonts:
        - Roboto
        - Open Sans
  - type: signing # this sets up the proper policy & signing files for signed images to work fully

